### ISSUE TITLE
API Dash rpm doesn't loads on Fedora 40 . Closes before it even starts

### ISSUE THREAD

**Issue by shivam-jainn** [foss42/apidash#463] opened 2024-09-08 15:18 UTC
**Describe the bug/problem**
When i click on apidash icon ,it's loads up the screen but closes immediately in 2 seconds .

**Steps to Reproduce the bug/problem**
1. Download it on Fedora 40 ( x86 rpm package)
2. Install it from software app on fedora
3. click run

**Expected behavior**
Should display a working app

**Device Info (The device where you encountered this issue):**
 - OS: Fedora 
 - Version: 40

**Comment by ashitaprasad** [comment] 2024-09-08 18:52
@shivam-jainn Can you confirm if you are running it on 32 bit or 64 bit CPU?

**Comment by shivam-jainn** [comment] 2024-09-08 18:54
64 bit

**Comment by ashitaprasad** [comment] 2024-09-08 18:56
@shivam-jainn  Thanks for the reply, will look into it.

**Comment by shivam-jainn** [comment] 2024-09-08 19:24
is it weird that this works now? but didn

**Comment by ashitaprasad** [comment] 2024-09-09 23:58
This is a bit weird, but thanks for confirming. Since it cannot be reproduced, for now I am closing this issue.

**Closed by ashitaprasad** 2024-09-09 23:58 UTC
Labels: bug
