### ISSUE TITLE
Feature: HTML Content Viewer Tab for Response Pane

### ISSUE THREAD

**Issue by chetanr25** [foss42/apidash#478] opened 2024-10-11 20:00 UTC
### Description
Currently, the response pane does not support viewing HTML content in a formatted way. A dedicated tab for rendering and previewing HTML responses would improve the user experience, especially when handling API responses that return HTML or sometimes error statuscodes with descriptions.

### Why It's Needed
- **Improved Usability:** For API responses containing HTML, it can be difficult to read the raw response. A formatted HTML viewer helps users understand and debug HTML content more effectively.
- **Consistent Experience:** Users who expect to view structured content (like JSON or headers) should have the same level of readability for HTML.

### Solution Implemented
- Added an **HTML Preview Tab** to the response pane, allowing users to view HTML responses in a formatted, rendered manner.
- Utilized the `flutter_html` package to render HTML content in a new tab.
- Added the tab next to "Response Body" and "Headers" for seamless navigation.

### Screenshots
Below are screenshots showing the new HTML Preview tab:

<p align="center">
  <img src="https://github.com/user-attachments/assets/93a17ec0-15ed-46bf-bd19-f557ff48d634" width="40%">
  <img src="https://github.com/user-attachments/assets/b852f6dd-00a6-4b2f-9775-41768c16b929" width="40%">
</p>

<p align="center">
  <img src="https://github.com/user-attachments/assets/a719b82b-2d41-495a-86e0-bd46c0d9d5d8" width="40%">
</p>

**Comment by chetanr25** [comment] 2024-10-11 20:02
Would love to hear any suggestions for improving this feature! Could I work on this issue if it aligns with the project’s direction?

**Comment by ashitaprasad** [comment] 2024-10-12 05:40
Duplicate of #155 
Please discuss on that thread.

**Closed by ashitaprasad** 2024-10-12 05:40 UTC
Labels: enhancement
