### ISSUE TITLE
Option to import json postman exported collections

### ISSUE THREAD

**Issue by ahmedtohamy1** [foss42/apidash#461] opened 2024-09-03 09:36 UTC
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
As title says that option is REALLLLY NEEDED

**Any other feedback you would like to provide regarding the site**
good ui and nice ram usage; my beloved flutter.

**Comment by ashitaprasad** [comment] 2024-09-03 10:56
Thank you for raising the issue @ahmedtohamy1 and for your feedback.
Closing it as it is a duplicate of an already open issue that we are working on.
https://github.com/foss42/apidash/issues/52

**Closed** 2024-09-03 10:56 UTC
Labels: enhancement
