### ISSUE TITLE
Bug: codgen error display when url is empty

### ISSUE THREAD

**Issue by PCoder23** [foss42/apidash#201] opened 2024-02-25 23:02 UTC
**Describe the bug/problem**
When the url is empty , every javascript and node js related cogen generates an error

**Steps to Reproduce the bug/problem**
Keep the url empty and gen code for js (axios) , js (fetch) , nodejs (axios), nodejs (fetch) and cUrl

![Screenshot 2024-02-26 042359](https://github.com/foss42/apidash/assets/85278795/8a6d7c91-f50e-497d-be06-b62495b9d170)

**Expected behavior**
Instead of showing error , it should indicate a message that the url is empty and you should fill it to generate code
 
**Device Info (The device where you encountered this issue):**
 - OS: Windows
 - Version: Windows 11

**Comment by animator** [comment] 2024-02-25 23:09
Duplicate of #157

**Closed by animator** 2024-02-25 23:09 UTC
Labels: bug
