### ISSUE TITLE
Local build failure on macOS 15.1.1

### ISSUE THREAD

**Issue by StormGear** [foss42/apidash#510] opened 2024-12-17 14:06 UTC
#### Describe the bug/problem
I am relatively new to the APIDash project. I wanted to build the macOS app locally, however I'm facing some build issues. It seems to have something to do with "audio_session", FlutterMacOS.h file and a Test module in the swift codebase.

#### Steps to Reproduce the bug/problem
- Run `flutter run` after following the setup guide for macOS in the Contributing guide.
<img width="1312" alt="Screenshot 2024-12-17 at 1 59 28 PM" src="https://github.com/user-attachments/assets/e09c2268-2e76-4e28-bd75-b335ee1ba534" />

#### Expected behavior
I expect the macOS debug app to run locally on my Macbook

#### Device Info (The device where you encountered this issue)
 - OS: MacOS
 - Version: Sequoia 15.1.1
 
#### Flutter Doctor

```
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale en-GH)
    • Flutter version 3.27.0 on channel stable at /Users/papakofi/Desktop/Flutter iOS/flutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (7 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/papakofi/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.96.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by ashitaprasad** [comment] 2024-12-17 15:50
@StormGear Can you kindly downgrade Flutter to the previous stable version and try again.

**Comment by StormGear** [comment] 2024-12-20 13:01
Thank you so much, I've got it to work now, I'll like to add how I resolved this issue. <br/>
*The problem* 
<img width="1312" alt="Screenshot 2024-12-20 at 12 55 07 PM" src="https://github.com/user-attachments/assets/68d04ba5-18c1-4f59-a1f6-5da7a81b9904" />
I indeed downgraded to Flutter 3.24.4 using fvm.
The desktop_drop module is not available for x86_64 architectures. <br/>
*The Solution*
<img width="1312" alt="Screenshot 2024-12-20 at 12 55 00 PM" src="https://github.com/user-attachments/assets/c16e2275-803f-4783-bb57-66b7b43dfbcf" />
The solution was to set `Build Active Architecture Only` to true.

**Comment by ashitaprasad** [comment] 2024-12-20 14:15
Thanks for investigating and finding the root cause of the issue @StormGear

**Comment by StormGear** [comment] 2024-12-23 08:59
Thanks for your assistance @ashitaprasad

**Comment by ashitaprasad** [comment] 2024-12-23 21:37
Closing this issue as it has now been documented in the [platform specific instructions](https://github.com/foss42/apidash/blob/main/doc/dev_guide/platform_specific_instructions.md).

**Closed by ashitaprasad** 2024-12-23 21:37 UTC
Labels: bug
