### ISSUE TITLE
CodeGen error when URL is empty

### ISSUE THREAD

**Issue by amankumarmahavar** [foss42/apidash#183] opened 2024-02-24 12:26 UTC
**Describe the bug/problem**
When the URL field is empty and you click on `view code` button, some codegen throws an error.

**Steps to Reproduce the bug/problem**
  1. Type something in URL field, 
  2. press view code button.
  3. select any language

   -    CURL
   - Node.js (fetch)
   - Javascript (fetch)
   -  Node.js (axios)
   - Javascript (axios)

  4. remove the URL text.

https://github.com/foss42/apidash/assets/72187898/a24b69af-d3da-49c3-ae1a-4cfeb9b423a7

**Expected behavior**
This should not show an error, instead  The entire code should be display with URL as `''`

**Device Info (The device where you encountered this issue):**
 - OS: [e.g. Windows, MacOS]
 - Version: [e.g. Catalina 10.15.7, Monterey 12.3.1, Windows 11 22H2]
 - Browser (only if you encountered the issue while running the web app): [e.g. chrome, safari]

**Comment by opxdelwin** [comment] 2024-02-24 14:17
I'll raise a PR soon, stay tuned!

**Comment by amankumarmahavar** [comment] 2024-02-24 14:39
@opxdelwin I think i got the solution

**Comment by animator** [comment] 2024-02-25 23:10
Duplicate of #157

**Closed by animator** 2024-02-25 23:10 UTC
Labels: bug, good first issue
